# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balanca', '0005_auto_20171207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to=settings.AUTH_USER_MODEL),
        ),
    ]
